### ISSUE TITLE
2017 Conference Season Planning

### ISSUE THREAD

**Issue by watson** [watson/hacker-conferences#18]
It would be nice to get an overview over where everybody is speaking or planning to attend this year ❤️✈️🎤  

If you like to participate, just fill out a column with your plans in this Google Spreadsheet 👉 
https://docs.google.com/spreadsheets/d/1FHK-Yif4P2TKBnzeTwTyMVLylZc-ip58KYwc6ehYrfE/edit?usp=sharing

**Comment by watson** [comment]
cc @feross @diasdavid @terezka @maxogden @yoshuawuyts @juliangruber @substack @dominictarr @mcollina @noffle @bcomnes @RichardLitt @dcposch @lrlna @whyrusleeping @MylesBorins

**Comment by mcollina** [comment]
👍

**Comment by daviddias** [comment]
This is an amazing idea! :D Thank you!

**Comment by MylesBorins** [comment]
Fantastic! I added a few more events that are on my radar. This is the spreadsheet I need in my life!

**Comment by feross** [comment]
Great idea!

**Comment by MylesBorins** [comment]
Seems like this is ready to close

**Comment by daviddias** [comment]
time for 2018?
